const FETCH_DATA_REQUEST_ALL_JOBS = 'FETCH_DATA_REQUEST_ALL_JOBS';
const FETCH_DATA_SUCCESS_ALL_JOBS = 'FETCH_DATA_SUCCESS_ALL_JOBS';
const FETCH_DATA_FAILURE_ALL_JOBS = 'FETCH_DATA_FAILURE_ALL_JOBS';

export {FETCH_DATA_REQUEST_ALL_JOBS, FETCH_DATA_SUCCESS_ALL_JOBS, FETCH_DATA_FAILURE_ALL_JOBS};
