const SEND_DATA_REQUEST_APPLY_TO_JOB = 'SEND_DATA_REQUEST_APPLY_TO_JOB';
const SEND_DATA_SUCCESS_APPLY_TO_JOB = 'SEND_DATA_SUCCESS_APPLY_TO_JOB';
const SEND_DATA_FAILURE_APPLY_TO_JOB = 'SEND_DATA_FAILURE_APPLY_TO_JOB';

export {SEND_DATA_REQUEST_APPLY_TO_JOB, SEND_DATA_SUCCESS_APPLY_TO_JOB, SEND_DATA_FAILURE_APPLY_TO_JOB};
