const FETCH_DATA_REQUEST_CASE_STUDIES = 'FETCH_DATA_REQUEST_CASE_STUDIES';
const FETCH_DATA_SUCCESS_CASE_STUDIES = 'FETCH_DATA_SUCCESS_CASE_STUDIES';
const FETCH_DATA_FAILURE_CASE_STUDIES = 'FETCH_DATA_FAILURE_CASE_STUDIES';

export {FETCH_DATA_REQUEST_CASE_STUDIES, FETCH_DATA_SUCCESS_CASE_STUDIES, FETCH_DATA_FAILURE_CASE_STUDIES};
