const FETCH_DATA_REQUEST_JOB_POSTINGS = 'FETCH_DATA_REQUEST_JOB_POSTINGS';
const FETCH_DATA_SUCCESS_JOB_POSTINGS = 'FETCH_DATA_SUCCESS_JOB_POSTINGS';
const FETCH_DATA_FAILURE_JOB_POSTINGS = 'FETCH_DATA_FAILURE_JOB_POSTINGS';

export {FETCH_DATA_FAILURE_JOB_POSTINGS, FETCH_DATA_SUCCESS_JOB_POSTINGS, FETCH_DATA_REQUEST_JOB_POSTINGS};
