const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
const LOADING_MESSAGE = 'LOADING_MESSAGE';

export {SEND_MESSAGE_SUCCESS, SEND_MESSAGE_REQUEST, SEND_MESSAGE_FAILURE, LOADING_MESSAGE};
